<?php

namespace Kartavik\Kivi\Tests\Unit\DB;

use Kartavik\Kivi\DB;
use PHPUnit\Framework\TestCase;

/**
 * Class OpenConnectionTest
 * @package Kartavik\Kivi\Tests\Unit\DB
 */
class OpenConnectionTest extends TestCase
{
    /** @var DB */
    protected $db;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
